---
title: "git_01"
author: "Jose Guzman"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

The outlook wasn't brilliant      
for the mudville nine that day:    
The score stood four to two, with but one inning    
more to play,    
and then when Cooney died at first, and Barrows    
did the same,  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

The city had withdrawn into itself  
 and left at last the country to the country;  
 When between whirls of snow not come to lie  
 and whirls of foliage not yet laid, there drove  
 A stranger to our yard, who looked the city.  
 
## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

“The sun was shining on the sea,  
 Shining with all his might:  
 He did his very best to make  
 The billows smooth and bright —  
And this was odd, because it was  
 The middle of the night.  

The moon was shining sulkily,  
 Because she thought the sun  
 Had got no business to be there  
 After the day was done —  
 “It’s very rude of him,” she said,  
“To come and spoil the fun.”  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

“I usually become a ghost to  
 those who no longer deserve  
 my time. I’ve never seen a point  
 in explaining my absence to  
 someone who failed to  
 appreciate my presence. You  
 don’t owe any explanations to  
 those who hurt you.”  
 